### ISSUE TITLE
Export/Import system broken

### ISSUE THREAD

**Issue by Xecular** [F3XTeam/RBX-Building-Tools#115]
When attempting to import anything into studio that I exported from f3x building tools, I noticed that all the import tool does is create an empty group with nothing in it. I have tried exporting several times to see if it was a one time error, but I can do it repeatedly with consistent results.

**Comment by GigsD4X** [comment]
Hi! Are you using the official version of the Building Tools by F3X tool or plugin? Also, are you trying to export any MeshPart or Union objects?

**Comment by Xecular** [comment]
Sorry, It didn't notify me that you replied so I am only seeing this now.

Yes. I am using the latest version of the official building tools along with the latest version of the import plugin. I am not trying to export MeshPart or Union objects.

Here is a code that is broken:

0xcd

**Comment by GigsD4X** [comment]
@Xecular This code appears to be importing properly; could your camera perhaps be looking elsewhere? Try pressing F when the import is complete to focus your camera on the build (which should get automatically selected).

**Comment by Xecular** [comment]
This is strange, all I get when I import it is an empty group.
![dwadaw](https://user-images.githubusercontent.com/32306390/32405213-7335fb92-c137-11e7-9fe0-acccf444d9fb.PNG)

**Comment by Xecular** [comment]
I just tried exporting something I made from BuildWorld for my friend's airline and I get "Could not import your creation" when I try to import it using the up to date plugin.

The code is 3mvl

**Comment by GigsD4X** [comment]
@Xecular Are HTTP requests enabled in the game settings of the place where you're attempting to import?

**Comment by Xecular** [comment]
Yes, they are enabled.

**Comment by SK-Fast** [comment]
I have the same issue. I use the official and HTTP also Enabled. It gives 521 Error

**Comment by willywillycow** [comment]
same, I found that a lot of time when I tries o export it said an unknown error occurred.

**Comment by tardisfromtornspace** [comment]
This problem keeps happening to me in a game called Be an alien: Renewal.

I discovered this happens if the creature contains any object different from the default "normal" rectangular prism.

**Comment by orangetagleaf** [comment]
Hello I have found the fix for myself for this F3X Import problem. First go to your plugins, then click manage plugins. After that you need to find Import F3X tool made by the correct and original creator, I turned auto update on but anyways, for me I see a few word that says "HTTP requests" I clicked that and it brought me to a new area with I check marked HTTP Request or "www.f3xteam.com" label. You may need to publish your place first not sure.
