### ISSUE TITLE
Provide a "tool restart" in the plugin

### ISSUE THREAD

**Issue by AnonymousPrayers** [F3XTeam/RBX-Building-Tools#39]
When using the tools in-game, and the tools break, you can just hit backspace and pick them back up, which reloads all the LocalScripts in the tool. What we need to be able to do is reload the plugin in some way, so that when a fatal error occurs, we don't need to go through and save it to roblox, then close it and open it again, then be able to build more, especially when you're forgetful like me and do things like #38.

**Comment by GigsD4X** [comment]
It seems that this isn't possible from plugin scripts due to the way they're loaded 🔍 Will focus on improving robustness to make up for this 👍
