### ISSUE TITLE
Client lags severely as you select lots of parts

### ISSUE THREAD

**Issue by GigsD4X** [F3XTeam/RBX-Building-Tools#48]

**Comment by ThatChristianGuy** [comment]
Studio crashes on plugin startup when selecting lots of items as well.

**Comment by GigsD4X** [comment]
Confirmed that lag is from hundreds/thousands of SelectionBoxes being created to highlight selected items.

**Comment by GigsD4X** [comment]
Fixed in 2.1.0 👍
