### ISSUE TITLE
The weld tool doesn't serve any use in Studio

### ISSUE THREAD

**Issue by GigsD4X** [F3XTeam/RBX-Building-Tools#66]
Because joints don't persist upon publishing places or reopening Studio, the weld tool is useless in Studio mode. It should probably provide more powerful, persistent welding features.

**Comment by TheClockArm** [comment]
Not only that, but the in-server welds created by the tool do not save into studio either. They just disappear.

**Comment by NNickey** [comment]
The welds could be made useful and SAVE if an option for changing it's "Archivable".

**Comment by GigsD4X** [comment]
If they were to remain alive though, there are inconsistency problems that arise. For example, if a part welded to another is deleted, then that deletion is undone and the part is restored, the weld is not restored even if it itself isn't deleted, so the whole undo/redo situation becomes unreliable

**Comment by AnonymousPrayers** [comment]
Maybe create a master script in ServerScriptService that uses ObjectValues to reweld objects on start of the game?

**Comment by GigsD4X** [comment]
That'd be super easy! But it'd break the whole concept of not leaving
tricky BT traces behind.

**Comment by AnonymousPrayers** [comment]
There's a concept of not leaving BT traces behind when the welds are named "BTWeld"?





On Tue, Jul 7, 2015 at 9:02 PM -0700, "Robert" <notifications@github.com> wrote:
That'd be super easy! But it'd break the whole concept of not leaving
tricky BT traces behind.

On Tue, Jul 7, 2015, 8:55 PM Zenon <notifications@github.com> wrote:

> Maybe create a master script in ServerScriptService that uses ObjectValues
> to reweld objects on start of the game?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/F3XTeam/ROBLOX-Building-Tools/issues/66#issuecomment-119415798>
> .
>


---
