### ISSUE TITLE
Current F3X GUI's Default Positions Issue

### ISSUE THREAD

**Issue by NNickey** [F3XTeam/RBX-Building-Tools#75]
Some of the default gui positions for the tool's setting isn't below the ChatGUI, and may cause constant frustration moving it back to a spot where you are able to click on the gui's without triggering the ChatGUI.
Could be because of testing F3x and didn't set the positions back to {0, 0},{0, 280}..

![screenshot_15](https://cloud.githubusercontent.com/assets/3466265/9288469/95c51970-4305-11e5-8e9b-8e0c3f3efbbf.png)
![screenshot_16](https://cloud.githubusercontent.com/assets/3466265/9288468/95c09382-4305-11e5-9f42-51e548dcdf8c.png)

**Comment by GigsD4X** [comment]
There needs to be a more elegant solution for this, there's gotta be somewhere you can get the size/position of the core GUIs. I'll check it out.

**Comment by NNickey** [comment]
There is a nasty fix, to set all CoreGUI's to default when the F3x tool starts.

**Comment by ThatChristianGuy** [comment]
http://wiki.roblox.com/index.php?title=API:Class/StarterGui/GetCore

**Comment by NNickey** [comment]
If you know how to fix it, you can fork it and apply the fix, and submit a request with your fork.

**Comment by ThatChristianGuy** [comment]
yeah ik I can, I'm working on some paint tool improvements atm but I might take a look at it after.

**Comment by ThatChristianGuy** [comment]
on second thought, using that method wouldn't work well with custom chat systems unless the custom chat script SetsCore
